### PR TITLE
Views

### PR DESCRIPTION
**Pull request by initseis**
## Description
In this branch I:

- Implemented the design from the sneak peek wireframes.

### users view
imagen

imagen

### posts view
imagen

imagen

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi, @sevinchek 

Good job so far! 👏🏼 

Great work on making the project requirements :clap:
You've done well-implementing project requirements, but there are still some issues which aren't been addressed yet 
 
## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.

- [ ] The server is running successfully, however, the data are not being displayed on the screen from the views, kindly check the controller implementation to fix the issue.
user-10

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by initseis** [comment]
> Hi, @sevinchek
> 
> Good job so far! 👏🏼
> 
> Great work on making the project requirements 👏 You've done well-implementing project requirements, but there are still some issues which aren't been addressed yet
> ## STATUS: CHANGES REQUESTED ♻️
> ### Changes requested.
> 
>     * [ ]  The server is running successfully, however, the data are not being displayed on the screen from the views, kindly check the controller implementation to fix the issue.
>       user-10
> 
> 
> #### Optional suggestions
> 
>     * N/A
> 
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding! 👏 👏 👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> #### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

Hi, @Emmyn5600. Thanks for the review. You are getting a blank page because you need to have data in the database to render in the view or do I need to put all the templates in hard code? Requirements don't ask that.

**Review by Emmyn5600 — APPROVED** [review]
Hi @sevinchek 

Good job 👏🏼

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Temmarie** [comment]
Hello  @sevinchek   :wave:

_This is an additional review as a result of the second opinion request._

Since the issue has been successfully resolved I will go ahead and close this ticket. All the best in your next projects!!
Keep rocking and happy coding:rocket:!

**Comment by Emmyn5600** [comment]
@Temmarie the issue has been resolved, I had to use `rails console` to add some data (post, comment, and user) because they can't hard code their application.

**Pull request merged**
